import {View, Text, TouchableOpacity, StyleSheet} from 'react-native';
import AppFonts from '../constants/Fonts';
import {RFPercentage, RFValue} from 'react-native-responsive-fontsize';
import {Colors, ScaleSizeUtils} from '../constants';

export const styles = StyleSheet.create({
  container: {backgroundColor: 'white', flex: 1},
  mainViewContainer: {backgroundColor: Colors.primary, flex: 1},
  image: {
    marginTop: '25%',
    alignSelf: 'center',
    width: '89%',
    height: '23%',
  },
  imagecontainer: {backgroundColor: 'white', height: '50%'},
  roundCircleRightTop: {
    height: 140,
    width: 140,
    borderRadius: 300,
    backgroundColor: Colors.white,
    position: 'absolute',
    right: -40,
    top: -40,
    zIndex: 2,
  },
  roundCircleLeftTop: {
    height: 140,
    width: 140,
    borderRadius: 300,
    backgroundColor: Colors.white,
    position: 'absolute',
    bottom: -40,
    left: -40,
    zIndex: 2,
  },
  welcomecontainer: {
    backgroundColor: Colors.primary,
    flex: 1,
    borderTopLeftRadius: 50,
    borderTopRightRadius: 50,
  },
  welcome: {
    fontSize: RFPercentage(3),
    color: 'white',
    marginTop: '15%',
    marginLeft: 15,
    fontFamily: AppFonts.FONT_INTER_BOLD,
    textAlign: 'center',
  },
  text: {
    color: 'white',
    fontSize: RFPercentage(2.5),
    marginLeft: 15,
    marginTop: '8%',
    fontFamily: AppFonts.FONT_INTER_REGULER,
  },
  signview: {
    marginTop: '15%',
    flexDirection: 'row',
    width: '90%',
    alignSelf: 'center',
    marginBottom: 20,
  },
  signtext: {
    color: 'white',
    borderRadius: 70,
    backgroundColor: 'black',
    padding: 20,
    paddingLeft: 40,
    paddingRight: 40,
    fontWeight: 'bold',
    fontSize: 23,
  },
  logtext: {
    color: 'black',
    borderRadius: 70,
    backgroundColor: 'white',
    padding: 20,
    paddingLeft: 45,
    paddingRight: 45,
    fontWeight: 'bold',
    fontSize: 23,
  },
  bottomView: {
    paddingTop: ScaleSizeUtils.DIMEN_MARGIN_EXTRA_LERGE,
    borderTopLeftRadius: 50,
    backgroundColor: 'white',
    borderTopRightRadius: 50,
  },
  bottomViewSignup: {
    paddingTop: ScaleSizeUtils.DIMEN_MARGIN_LARGE,
    borderTopLeftRadius: 50,
    backgroundColor: 'white',
    borderTopRightRadius: 50,
  },
  bottom_modal: {
    flexDirection: 'row',
    flex: 1,
    alignItems: 'center',
    justifyContent: 'space-around',
  },
  profile_image: {
    width: 150,
    height: 150,
  },
  profile_view: {
    backgroundColor: Colors.white,
    padding: 10,
    position: 'absolute',
    borderRadius: 100,
    right: 0,
    bottom: 0,
  },
  camera_icon: {
    width: 30,
    height: 30,
    tintColor: Colors.primary,
  },
  camera_touch: {
    width: ScaleSizeUtils.DIMENSTION_LARGE,
    height: ScaleSizeUtils.DIMENSTION_LARGE,
    tintColor: Colors.primary,
  },
  modal_bottom_style: {
    width: '100%',
    height: '20%',
    backgroundColor: 'white',
    elevation: 10,
    position: 'absolute',
    bottom: 0,
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
  },
  forgot: {
    fontSize: RFPercentage(2.2),
    alignSelf: 'flex-end',
    marginRight: 25,
    marginTop: 7,
    color: Colors.dark_gray,
  },
  already: {
    color: 'black',
    fontFamily: AppFonts.FONT_INTER_BOLD,
    fontSize: RFPercentage(2.5),
  },
  addChild: {
    color: 'black',
    fontFamily: AppFonts.FONT_INTER_BOLD,
    fontSize: RFPercentage(2.5),
    alignSelf: 'center',
    marginTop: 10,
  },
  signinbtn: {
    color: 'blue',
    fontFamily: AppFonts.FONT_INTER_BOLD,
    fontSize: RFPercentage(2.5),
  },
  alreadyview: {
    flexDirection: 'row',
    marginBottom: 10,
    marginTop: 15,
    alignSelf: 'center',
  },
  lock: {
    height: ScaleSizeUtils.DIMEN_MEDIUM,
    width: ScaleSizeUtils.DIMEN_MEDIUM,
    alignSelf: 'center',
  },
  underlineStyleHighLighted: {
    backgroundColor: 'white',
  },
  underlineStyleBase: {
    width: 65,
    height: 65,
    borderWidth: 3,
    borderRadius: 20,
    fontSize: 26,
    fontWeight: '600',
    color: 'black',
  },
  otp: {width: '80%', height: 20, marginTop: 30, alignSelf: 'center'},
  resend: {
    color: '#5A5A5A',
    fontWeight: '600',
    fontSize: 18,
    marginTop: '9%',
    alignSelf: 'center',
  },
  radioForm: {
    flexDirection: 'row',
    width: '90%',
    alignSelf: 'center',
    alignContent: 'center',
  },
  uploadBox: {
    width: '90%',
    backgroundColor: '#FFEFEC',
    alignSelf: 'center',
    alignItems: 'center',
    borderRadius: 20,
    alignContent: 'center',
    padding: 30,
    marginBottom: 10,
  },
  bottom_modal: {
    flexDirection: 'row',
    flex: 1,
    alignItems: 'center',
    justifyContent: 'space-around',
  },
  camera_touch: {
    width: ScaleSizeUtils.DIMENSTION_LARGE,
    height: ScaleSizeUtils.DIMENSTION_LARGE,
    tintColor: Colors.primary,
  },
  modal_bottom_style: {
    width: '100%',
    height: '20%',
    backgroundColor: 'white',
    elevation: 10,
    position: 'absolute',
    bottom: 0,
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
  },
  Listview: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
  },
  ListviewValue: {
    fontSize: RFPercentage(2.5),
    color: Colors.black,
    flex: 0.8,
    textAlign: 'left',
  },
  ListviewLable: {
    fontSize: RFPercentage(2.5),
    color: Colors.black,
    flex: 0.3,
  },
  child_image: {
    width: 50,
    height: 50,
    alignSelf: 'center',
    borderRadius: 50,
  },
  school_name: {
    color: Colors.black,
    fontFamily: AppFonts.FONT_INTER_MEDIUM,
    fontSize: RFPercentage(2.5),
    marginBottom: 10,
    alignSelf: 'center',
  },
  seprator: {
    height: 50,
    width: 20,
  },
  paymentText: {
    color: Colors.black,
    fontFamily: AppFonts.FONT_INTER_REGULER,
    fontSize: RFPercentage(3.5),
    marginBottom: 10,
  },
  paymentDes: {
    color: Colors.gray,
    fontFamily: AppFonts.FONT_INTER_REGULER,
    fontSize: RFPercentage(2.4),
    marginTop: 20,
  },
  paymentTime: {
    color: Colors.black,
    fontFamily: AppFonts.FONT_INTER_BOLD,
    fontSize: RFPercentage(2.5),
    marginTop: 20,
  },
  cardBoxContainer: {
    padding: 15,
    borderWidth: 1,
    borderColor: Colors.gray,
    marginTop: 15,
    borderRadius: 15,
  },
  paidAmount: {
    color: Colors.black,
    fontFamily: AppFonts.FONT_INTER_REGULER,
    fontSize: RFPercentage(2),
  },
  amountText: {
    color: Colors.black,
    fontFamily: AppFonts.FONT_INTER_BOLD,
    fontSize: RFPercentage(2.2),
  },
  shareIcon: {
    height: 50,
    width: 20,
    tintColor: Colors.black,
    resizeMode: 'contain',
  },
  profile_title: {
    fontFamily: AppFonts.FONT_INTER_MEDIUM,
    fontSize: RFPercentage(2.5),
    marginTop: 10,
    textAlign: 'center',
    color: Colors.black,
  },
  profile_mobile: {
    fontFamily: AppFonts.FONT_INTER_REGULER,
    fontSize: RFPercentage(2),
    marginTop: 10,
    textAlign: 'center',
    color: Colors.gray,
  },
});
