/* eslint-disable import/no-cycle */

/* AUTH */

export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';
export const CLEAR_LOGIN_USER = 'CLEAR_LOGIN_USER';

export const REGISTER_USER = 'REGISTER_USER';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR';
export const CLEAR_REGISTER_USER = 'CLEAR_REGISTER_USER';

export const GET_TOKEN_REQUEST = 'GET_TOKEN_REQUEST';
export const GET_TOKEN_SUCCESS = 'GET_TOKEN_SUCCESS';
export const GET_TOKEN_ERROR = 'GET_TOKEN_ERROR';

export const GET_SCHOOL_REQUEST = 'GET_SCHOOL_REQUEST';
export const GET_SCHOOL_SUCCESS = 'GET_SCHOOL_SUCCESS';
export const GET_SCHOOL_ERROR = 'GET_SCHOOL_ERROR';

export const RESEND_OTP_REQUEST = 'RESEND_OTP_REQUEST';
export const RESEND_OTP__SUCCESS = 'RESEND_OTP__SUCCESS';
export const RESEND_OTP__ERROR = 'RESEND_OTP__ERROR';
export const CLEAR_RESEND_OTP = 'CLEAR_RESEND_OTP';

export const VERIFY_OTP_REQUEST = 'VERIFY_OTP_REQUEST';
export const VERIFY_OTP__SUCCESS = 'VERIFY_OTP__SUCCESS';
export const VERIFY_OTP__ERROR = 'VERIFY_OTP__ERROR';
export const CLEAR_VERIFY_OTP = 'CLEAR_VERIFY_OTP';

export const FORGET_PASSWORD_REQUEST = 'FORGET_PASSWORD_REQUEST';
export const FORGET_PASSWORD__SUCCESS = 'FORGET_PASSWORD__SUCCESS';
export const FORGET_PASSWORD__ERROR = 'FORGET_PASSWORD__ERROR';
export const CLEAR_FORGET_PASSWORD = 'CLEAR_FORGET_PASSWORD';

export const RESET_PASSWORD_REQUEST = 'RESET_PASSWORD_REQUEST';
export const RESET_PASSWORD__SUCCESS = 'RESET_PASSWORD__SUCCESS';
export const RESET_PASSWORD__ERROR = 'RESET_PASSWORD__ERROR';
export const CLEAR_RESET_PASSWORD = 'CLEAR_RESET_PASSWORD';

export const GET_PROFILE_DETAILS_REQUEST = 'GET_PROFILE_DETAILS_REQUEST';
export const GET_PROFILE_DETAILS_SUCCESS = 'GET_PROFILE_DETAILS_SUCCESS';
export const GET_PROFILE_DETAILS_ERROR = 'GET_PROFILE_DETAILS_ERROR';
export const CLEAR_PROFILE_DETAILS = 'CLEAR_PROFILE_DETAILS';

export const GET_PROFILE_UPDATE_REQUEST = 'GET_PROFILE_UPDATE_REQUEST';
export const GET_PROFILE_UPDATE_SUCCESS = 'GET_PROFILE_UPDATE_SUCCESS';
export const GET_PROFILE_UPDATE_ERROR = 'GET_PROFILE_UPDATE_ERROR';
export const CLEAR_PROFILE_UPDATE = 'CLEAR_PROFILE_UPDATE';

export const GET_CHANGE_PASSWORD_REQUEST = 'GET_CHANGE_PASSWORD_REQUEST';
export const GET_CHANGE_PASSWORD_SUCCESS = 'GET_CHANGE_PASSWORD_SUCCESS';
export const GET_CHANGE_PASSWORD_ERROR = 'GET_CHANGE_PASSWORD_ERROR';
export const CLEAR_CHANGE_PASSWORD = 'CLEAR_CHANGE_PASSWORD';

export const GET_UPLOAD_PHOTO_REQUEST = 'GET_UPLOAD_PHOTO_REQUEST';
export const GET_UPLOAD_PHOTO_SUCCESS = 'GET_UPLOAD_PHOTO_SUCCESS';
export const GET_UPLOAD_PHOTO_ERROR = 'GET_UPLOAD_PHOTO_ERROR';
export const CLEAR_UPLOAD_PHOTO = 'CLEAR_UPLOAD_PHOTO';

/* NON AUTH */

export const GET_BANNER_REQUEST = 'GET_BANNER_REQUEST';
export const GET_BANNER_SUCCESS = 'GET_BANNER_SUCCESS';
export const GET_BANNER_ERROR = 'GET_BANNER_ERROR';
export const CLEAR_BANNER = 'CLEAR_BANNER';

export const GET_MEAL_TYPE_REQUEST = 'GET_MEAL_TYPE_REQUEST';
export const GET_MEAL_TYPE_SUCCESS = 'GET_MEAL_TYPE_SUCCESS';
export const GET_MEAL_TYPE_ERROR = 'GET_MEAL_TYPE_ERROR';
export const CLEAR_MEAL_TYPE = 'CLEAR_MEAL_TYPE';

export const GET_FOOD_MENU_REQUEST = 'GET_FOOD_MENU_REQUEST';
export const GET_FOOD_MENU_SUCCESS = 'GET_FOOD_MENU_SUCCESS';
export const GET_FOOD_MENU_ERROR = 'GET_FOOD_MENU_ERROR';
export const CLEAR_FOOD_MENU = 'CLEAR_FOOD_MENU';

export const GET_STUDENT_DETAILS_REQUEST = 'GET_STUDENT_DETAILS_REQUEST';
export const GET_STUDENT_DETAILS_SUCCESS = 'GET_STUDENT_DETAILS_SUCCESS';
export const GET_STUDENT_DETAILS_ERROR = 'GET_STUDENT_DETAILS_ERROR';
export const CLEAR_STUDENT_DETAILS = 'CLEAR_STUDENT_DETAILS';

export const CREATE_SUBSCRIPTION_ORDER_REQUEST =
  'CREATE_SUBSCRIPTION_ORDER_REQUEST';
export const CREATE_SUBSCRIPTION_ORDER_SUCCESS =
  'CREATE_SUBSCRIPTION_ORDER_SUCCESS';
export const CREATE_SUBSCRIPTION_ORDER__ERROR =
  'CREATE_SUBSCRIPTION_ORDER__ERROR';
export const CLEAR_SUBSCRIPTION_ORDER = 'CLEAR_SUBSCRIPTION_ORDER';

export const GET_CART_ITEM_REQUEST = 'GET_CART_ITEM_REQUEST';
export const GET_CART_ITEM_SUCCESS = 'GET_CART_ITEM_SUCCESS';
export const GET_CART_ITEM_ERROR = 'GET_CART_ITEM_ERROR';
export const CLEAR_CART_ITEM = 'CLEAR_CART_ITEM';

export const CREATE_STUDENT_DETAILS_REQUEST = 'CREATE_STUDENT_DETAILS_REQUEST';
export const CREATE_STUDENT_DETAILS_SUCCESS = 'CREATE_STUDENT_DETAILS_SUCCESS';
export const CREATE_STUDENT_DETAILS_ERROR = 'CREATE_STUDENT_DETAILS_ERROR';
export const CLEAR_CREATE_STUDENT_DETAILS = 'CLEAR_CREATE_STUDENT_DETAILS';

export const UPDATE_STUDENT_DETAILS_REQUEST = 'UPDATE_STUDENT_DETAILS_REQUEST';
export const UPDATE_STUDENT_DETAILS_SUCCESS = 'UPDATE_STUDENT_DETAILS_SUCCESS';
export const UPDATE_STUDENT_DETAILS_ERROR = 'UPDATE_STUDENT_DETAILS_ERROR';
export const CLEAR_UPDATE_STUDENT_DETAILS = 'CLEAR_UPDATE_STUDENT_DETAILS';

export const DELETE_STUDENT_DETAILS_REQUEST = 'DELETE_STUDENT_DETAILS_REQUEST';
export const DELETE_STUDENT_DETAILS_SUCCESS = 'DELETE_STUDENT_DETAILS_SUCCESS';
export const DELETE_STUDENT_DETAILS_ERROR = 'DELETE_STUDENT_DETAILS_ERROR';
export const CLEAR_DELETE_STUDENT_DETAILS = 'CLEAR_DELETE_STUDENT_DETAILS';

export const GET_STUDENT_SUBSCRIPTION_ORDER_REQUEST =
  'GET_STUDENT_SUBSCRIPTION_ORDER_REQUEST';
export const GET_STUDENT_SUBSCRIPTION_SUCCESS =
  'GET_STUDENT_SUBSCRIPTION_SUCCESS';
export const GET_STUDENT_SUBSCRIPTION_ERROR = 'GET_STUDENT_SUBSCRIPTION_ERROR';
export const CLEAR_GET_STUDENT_SUBSCRIPTION = 'CLEAR_GET_STUDENT_SUBSCRIPTION';

export const GET_ORDER_DETAILS_REQUEST = 'GET_ORDER_DETAILS_REQUEST';
export const GET_ORDER_DETAILS_SUCCESS = 'GET_ORDER_DETAILS_SUCCESS';
export const GET_ORDER_DETAILS_ERROR = 'GET_ORDER_DETAILS_ERROR';
export const CLEAR_GET_ORDER_DETAILS = 'CLEAR_GET_STUDENT_SUBSCRIPTION';

export const ALL_STATE_CLEAR_REQUEST = 'ALL_STATE_CLEAR_REQUEST';

export const ALL_AUTH_STATE_CLEAR_REQUEST = 'ALL_AUTH_STATE_CLEAR_REQUEST';

//Delivery Person

export const GET_DELIVERY_DASHBOARD_DETAILS_REQUEST =
  'GET_DELIVERY_DASHBOARD_DETAILS_REQUEST';
export const GET_DELIVERY_DASHBOARD_DETAILS_SUCCESS =
  'GET_DELIVERY_DASHBOARD_DETAILS_SUCCESS';
export const GET_DELIVERY_DASHBOARD_DETAILS_FAILURE =
  'GET_DELIVERY_DASHBOARD_DETAILS_FAILURE';
export const CLEAR_DELIVERY_DASHBOARD_DETAILS_REQUEST =
  'CLEAR_DELIVERY_DASHBOARD_DETAILS_REQUEST';

export const GET_DELIVERY_HISTORY_DETAILS_REQUEST =
  'GET_DELIVERY_HISTORY_DETAILS_REQUEST';
export const GET_DELIVERY_HISTORY_DETAILS_SUCCESS =
  'GET_DELIVERY_HISTORY_DETAILS_SUCCESS';
export const GET_DELIVERY_HISTORY_DETAILS_FAILURE =
  'GET_DELIVERY_HISTORY_DETAILS_FAILURE';
export const CLEAR_DELIVERY_HISTORY_DETAILS_REQUEST =
  'CLEAR_DELIVERY_HISTORY_DETAILS_REQUEST';

export const UPDATE_ORDER_STATUS_REQUEST = 'UPDATE_ORDER_STATUS_REQUEST';
export const UPDATE_ORDER_STATUS_SUCCESS = 'UPDATE_ORDER_STATUS_SUCCESS';
export const UPDATE_ORDER_STATUS_FAILURE = 'UPDATE_ORDER_STATUS_FAILURE';
export const CLEAR_ORDER_STATUS_REQUEST = 'CLEAR_ORDER_STATUS_REQUEST';

export const GET_TRANCTION_SUCCESS_REQUEST = 'GET_TRANCTION_SUCCESS_REQUEST';
export const GET_TRANCTION_SUCCESS_SUCCESS = 'GET_TRANCTION_SUCCESS_SUCCESS';
export const GET_TRANCTION_SUCCESS_FAILURE = 'GET_TRANCTION_SUCCESS_FAILURE';
export const CLEAR_TRANCTION_SUCCESS_REQUEST =
  'CLEAR_TRANCTION_SUCCESS_REQUEST';

export const GET_PAYMENT_HISTORY_REQUEST = 'GET_PAYMENT_HISTORY_REQUEST';
export const GET_PAYMENT_HISTORY_SUCCESS = 'GET_PAYMENT_HISTORY_SUCCESS';
export const GET_PAYMENT_HISTORY_FAILURE = 'GET_PAYMENT_HISTORY_FAILURE';
export const CLEAR_PAYMENT_HISTORY_REQUEST = 'CLEAR_PAYMENT_HISTORY_REQUEST';

export const GET_CANCEL_MEAL_TYPE_REQUEST = 'GET_CANCEL_MEAL_TYPE_REQUEST';
export const GET_CANCEL_MEAL_TYPE_SUCCESS = 'GET_CANCEL_MEAL_TYPE_SUCCESS';
export const GET_CANCEL_MEAL_TYPE_FAILURE = 'GET_CANCEL_MEAL_TYPE_FAILURE';
export const CLEAR_CANCEL_MEAL_TYPE = 'CLEAR_CANCEL_MEAL_TYPE';

export const GET_DELETE_ACCOUNT_REQUEST = 'GET_DELETE_ACCOUNT_REQUEST';
export const GET_DELETE_ACCOUNT_SUCCESS = 'GET_DELETE_ACCOUNT_SUCCESS';
export const GET_DELETE_ACCOUNT_FAILURE = 'GET_DELETE_ACCOUNT_FAILURE';
export const CLEAR_GET_DELETE_ACCOUNT = 'CLEAR_GET_DELETE_ACCOUNT';

export const GET_UPDATE_PASSWORD_REQUEST = 'GET_UPDATE_PASSWORD_REQUEST';
export const GET_UPDATE_PASSWORD_SUCCESS = 'GET_UPDATE_PASSWORD_SUCCESS';
export const GET_UPDATE_PASSWORD_FAILURE = 'GET_UPDATE_PASSWORD_FAILURE';
export const CLEAR_GET_UPDATE_PASSWORD = 'CLEAR_GET_UPDATE_PASSWORD';

export const GET_DELETE_ITEMS_REQUEST = 'GET_DELETE_ITEMS_REQUEST';
export const GET_DELETE_ITEMS_SUCCESS = 'GET_DELETE_ITEMS_SUCCESS';
export const GET_DELETE_ITEMS_FAILURE = 'GET_DELETE_ITEMS_FAILURE';
export const CLEAR_GET_DELETE_ITEMS = 'CLEAR_GET_DELETE_ITEMS';

export const GET_PACKCHARGIES_APPLY_REQUEST = 'GET_PACKCHARGIES_APPLY_REQUEST';
export const GET_PACKCHARGIES_APPLY_SUCCESS = 'GET_PACKCHARGIES_APPLY_SUCCESS';
export const GET_PACKCHARGIES_APPLY_FAILURE = 'GET_PACKCHARGIES_APPLY_FAILURE';
export const CLEAR_GET_PACKCHARGIES_APPLY = 'CLEAR_GET_PACKCHARGIES_APPLY';

export const GET_BIRTHDAY_SETTING_REQUEST = 'GET_BIRTHDAY_SETTING_REQUEST';
export const GET_BIRTHDAY_SETTING_SUCCESS = 'GET_BIRTHDAY_SETTING_SUCCESS';
export const GET_BIRTHDAY_SETTING_FAILURE = 'GET_BIRTHDAY_SETTING_FAILURE';
export const CLEAR_BIRTHDAY_SETTING_REQUEST = 'CLEAR_BIRTHDAY_SETTING_REQUEST';

export const GET_CREATE_BIRTDAYPARTY_REQUEST =
  'GET_CREATE_BIRTDAYPARTY_REQUEST';
export const GET_CREATE_BIRTDAYPARTY_SUCCESS =
  'GET_CREATE_BIRTDAYPARTY_SUCCESS';
export const GET_CREATE_BIRTDAYPARTY_FALIURE =
  'GET_CREATE_BIRTDAYPARTY_FALIURE';
export const CLEAR_CREATE_BIRTDAYPARTY_REQUEST =
  'CLEAR_CREATE_BIRTDAYPARTY_REQUEST';

export const GET_CREATE_RATING_REQUEST = 'GET_CREATE_RATING_REQUEST';
export const GET_CREATE_RATING_SUCCESS = 'GET_CREATE_RATING_SUCCESS';
export const GET_CREATE_RATING_FAILURE = 'GET_CREATE_RATING_FAILURE';
export const CLEAR_RATING_REQUEST = 'CLEAR_RATING_REQUEST';

export * from './auth/actions';
